### ISSUE TITLE
isEmpty, isNotEmpty is not available.

### ISSUE THREAD

**Issue by narusas** [mybatis/ibatis2mybatis#2]
So, I wrote xslt snippet .

<code>
<xsl:template match="isEmpty">
	<xsl:element name="if">
		<xsl:attribute name="test">
		<xsl:if test="substring-before(@property, '.')">
			<xsl:value-of select="substring-before(@property, '.')" /><xsl:text> == '' or </xsl:text>
		</xsl:if>
		<xsl:value-of select="@property" /><xsl:text> == ''</xsl:text></xsl:attribute>
		<xsl:value-of select="@prepend" />
  		<xsl:apply-templates/>
  	</xsl:element>
</xsl:template>

<xsl:template match="isNotEmpty">
	<xsl:element name="if">
		<xsl:attribute name="test">
		<xsl:if test="substring-before(@property, '.')">
			<xsl:value-of select="substring-before(@property, '.')" /><xsl:text> != '' and </xsl:text>
		</xsl:if>
		<xsl:value-of select="@property" /><xsl:text> != ''</xsl:text></xsl:attribute>
		<xsl:value-of select="@prepend" />
  		<xsl:apply-templates/>
  	</xsl:element>
</xsl:template>
</code>

**Comment by hazendaz** [comment]
Code has been merged.
