### ISSUE TITLE
hello. i dont load http://www.ibatis.com/dtd/sql-map-2.dtd it have error 

### ISSUE THREAD

**Issue by heroLi** [mybatis/ibatis2mybatis#44]
javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Unexpected end of file from server
 
can you help me? if have other method to download it? like local?

**Comment by heroLi** [comment]
![image](https://github.com/user-attachments/assets/ee470509-0b91-4da4-9d3e-99c21166533a)
thanks

**Comment by harawata** [comment]
Hello @heroLi ,

#6 may fix your problem.
I'll see if we can merge the pull request, but for now, you can 1) apply the changes manually or 2) install [GitHub CLI](https://cli.github.com/) and type the following commands in Terminal.app.

```sh
cd /Users/lixiao167/Desktop/ibatis2mybatis-ibatis2mybatis-1.1.0
gh pr checkout 6
ant
```

**Comment by harawata** [comment]
#6 is merged.
